server:
  port: 9100
spring:
  application:
    name: org.lixue.helloworld
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver2:9002/eureka,http://eurekaserver1:9001/eureka