server:
  port: 9001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: eurekaserver1
  client:
    service-url:
      defaultZone: http://eurekaserver2:9002/eureka